version: '3'
services:
  demo:
      build:
        context: .
      ports:
        - 3000:3000        
      volumes:
        - .:/home/app/photo-stories/
        - /home/app/photo-stories/node_modules/
      command: yarn run start
  test:
      build:
        context: .
      environment:
        - CI=true        
      volumes:
        - .:/home/app/photo-stories/
        - /home/app/photo-stories/node_modules/
      command: yarn run test
  storybook:
      build:
        context: .
      ports:
        - 9009:9009        
      volumes:
        - .:/home/app/photo-stories/
        - /home/app/photo-stories/node_modules/
      command: yarn run storybook      